### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by dbof10** [fasiha/ebisu-java#1]
Is this lib up-to-date compare to js and python counterparts? How do we keep track of the last change in python?

**Comment by fasiha** [comment]
Thanks for writing, no, unfortunately this repo is a major version behind the JS/Python code (which are in lock-step since I know those languages well whereas I’m huge newbie at Java 😅). I will update the code to match Python Ebisu 1.0.0 and publish to Sonatype for easier reuse.

Please feel free to ping me regularly if I slack off on this. Thank you for reaching out!

**Comment by fasiha** [comment]
@dbof10 I'm total newb to Java ecosystem, how do *you* prefer to install open-source packages as dependencies in your Java projects?

I ask because, once I make changes to the code in this repo to match 1.0's algorithm, I don't know how to assign it a version number or where publish it—is Sonatype the answer?

Though I hate to ask this of you, any hints about your optimal workflow will be appreciated!

**Comment by dbof10** [comment]
can you take a look at https://medium.com/@erluxman/publishing-java-android-kotlin-libraries-on-jitpack-b33d0d26dc8a?

Normally, people just do
```compile group: 'io.reactivex', name: 'rxjava', version: '1.3.8'``` in their gradle file

Currently, we don't build tool to distribute. mostly people will use `gradle` (similar to `pip`).
I think can you push your `1.0`. I will have a PR for the distribution setup.
You can take a look at a popular java library, you can see how they set up
https://github.com/ReactiveX/RxJava

**Comment by dbof10** [comment]
`Sonatype` is a bit lengthy to publish. I think we should use jitpack for now. It helps us with the set up. What we need to do is just, create a tag for release version.

**Comment by dbof10** [comment]
@fasiha  what is the update? are you working 1.0 or build tools setup? Can you update the code first?

**Comment by fasiha** [comment]
I'm updating code, right now!, to match JavaScript/Python Ebisu 1.0! Please stand by I should have that merged in a few minutes. Beating tests into submission.

**Comment by dbof10** [comment]
thanks for your quick response 😆

**Comment by fasiha** [comment]
Well, took a bit more than a few minutes but have pushed something that I'm confident works.

I'm going to try and figure out how to import a JSON file containing test inputs and outputs from the reference Python implementation and make sure those work, but in the meantime, please check it out.

I'm also going to add the TXT record to aldebrn.me DNS per JitPack docs to prepare for that. How exciting!

**Comment by fasiha** [comment]
Specifically, 7d1dba3b1840d36d237cb8bca4003c387bcb9d4a is the commit I just pushed.

**Comment by dbof10** [comment]
welcome to JVM world. In the mean while, I suggest you to look at Kotlin Native https://kotlinlang.org/docs/reference/native-overview.html. If you want to maintain this project long term, Kotlin Native is the best choice since it can produce java code, native (swift, c++), js code. It helps a lot, more platforms can use Ebisu than just python  😆

**Comment by dbof10** [comment]
Is the test shared with python and js by json file?

**Comment by fasiha** [comment]
Thank you!, I've read Steve Yegge's celebration of Kotlin and with both his and your recommendation, I'm planning on trying out Kotlin and porting Ebisu to it too!

I just pushed 8312da53771c8aef05fdd500f4f1f8aec105ceb0 which adds a test against the reference implementation and resulting bugfixes! Yes, that's the JSON file shared by Python and JS implementations.

**Comment by fasiha** [comment]
https://jitpack.io/#me.aldebrn/ebisu-java/v1.0 😄!!!

**Comment by dbof10** [comment]
🎉 🎉 🎉 🎉 🎉 🎉

**Comment by fasiha** [comment]
https://jitpack.io/me/aldebrn/ebisu-java/v1.0.2/build.log has an error, because JitPack doesn't like the `<release>` in my pom.xml, but I can't build it locally without that. I will debug this tomorrow 😴

**Comment by fasiha** [comment]
JitPack error fixed by telling it to use Java9.
