### ISSUE TITLE
Check if a fact is internalised

### ISSUE THREAD

**Issue by dbof10** [fasiha/ebisu-java#5]
hey thank you for the library again. my question is not really related to Ebisu. After a student reviews a fact, does some quizzes to improve recall. How do we know if he internalises that fact he learn? Is there any algorithm out there, any way, any formula to achieve this?

**Comment by fasiha** [comment]
The way I think about this is remembering the studies that have shown how medical doctors forget what they learnt in medical school in 5–10 years if they don't review it. If this is the case, can you ever really say that anything is truly internalized? So the idea with SRS (spaced repetition systems) is to not risk forgetting something you thought you'd "internalized". That is, as you successfully answer quizzes, the halflife of the flashcard increases till it is several years—you'll never forget this flashcard if you review it every five years.

There may be ways to improve on this. In memorizing vocabulary in foreign language learning, if the vocabulary is common, you can be confident that the student will encounter it outside the quiz app, and maybe you can incorporate that information and delay quizzes for it. Or maybe your quiz app is aware of the pages the user bookmarks—assuming the user has read them, the quiz app can know what vocabulary the user has recently used. Tricks like this might help avoid the problem of wasting time reviewing flashcards that you know.

But in the end, it's always possible that a fact that a user knows now will not be reviewed for years at a time. If you want to ensure the user remembers it, the SRS has to do its job and review it periodically.

Does that make sense?

**Comment by dbof10** [comment]
thank you for your input
