### ISSUE TITLE
How difficult would it be to port Ebisu to C#?

### ISSUE THREAD

**Issue by rs-mobitech** [fasiha/ebisu-java#6]
I have a platform that uses C# so it's a problem for me that there's no C# version.  Do you have any ideas how difficult it would be to port the code to C#? Are there any obstacles such as the availability of libraries that you can think of?

**Comment by fasiha** [comment]
Not hard! I answered at https://github.com/fasiha/ebisu/issues/28#issuecomment-635251314

**Comment by fasiha** [comment]
@rscholey see https://github.com/fasiha/ebisu-java/issues/8, looks like a C# port has been made!
