### ISSUE TITLE
Requesting an update of the Java code to use the Ebisu 2.0 algorithm

### ISSUE THREAD

**Issue by rs-mobitech** [fasiha/ebisu-java#7]
I would like to start soon porting the code to C#.  Once completed I would be happy to make this available to you so we could have another open source C# port. 

When you have time available it would be a great help if you could port the code to the Ebisu 2.0 algorithm. 

Thanks

**Comment by fasiha** [comment]
Just pushed version 2.0 & published to JitPack!

Also published version 2.0 of Ebisu.js on npm https://www.npmjs.com/package/ebisu-js which follows the layout of the Python code more closely than this Java version (since I am noob at OOP).
